
// Type definitions for custom tables not in the Supabase autogenerated types

export interface NavItem {
  id: string;
  label: string;
  href: string;
  position: number;
  type: string;
  created_at?: string;
  updated_at?: string;
}

export interface ConfigItem {
  id: string;
  name: string;
  value: string;
  created_at?: string;
  updated_at?: string;
}
