// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xckwsujivhpvsafhyrls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhja3dzdWppdmhwdnNhZmh5cmxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NjMzOTYsImV4cCI6MjA2MzQzOTM5Nn0.UAcKBSi7zzoh_U072Kd5YhOOudg6DqNCoSW_zy5McAE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);